### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by nikku**

### CODE REVIEW

**Comment by philippfromme** [comment]
So the point of this is to have a test case verifying that the path intersection fails for this specific case?

**Review by barmac — APPROVED** [review]
🙈 -> ✅

**Comment by philippfromme** [comment]
The test is confusing. It looks like we're turning a bug into expected behavior. Good luck understanding that this test is verifying a bug in 6 months. 🙈

**Comment by nikku** [comment]
The user specified a clear scenario that was broken. [The test](https://github.com/bpmn-io/path-intersection/pull/20/commits/f79e3f34e14edac0a6ff3f43525bf271c6e69dea) you're likely referring to verifies that it is not broken anymore, cf. [this code sandbox](https://codesandbox.io/s/trusting-goldberg-4riuk?file=/src/index.js).

Anything wrong with this? Can/should we somehow address this one in a different manner?

**Comment by philippfromme** [comment]
Ah, so the fix wasn't part of this PR. Now I get it. All good!

**Comment by nikku** [comment]
Exactly. So we're on the same page. Great :rose:

**Pull request merged**
