### PR TITLE
Optimize iteration count for lines without slope

### LINKED ISSUE #9: Optimize intersection of straight lines
__Is your feature request related to a problem? Please describe__

Our intersection finding algorithm is as follows:

_(1) For each path_ 

* Path is cut into segments
* Each segment is converted to a bezier curve
* Each bezier curve segment is cut into chunks (bezier clipping) that are treated as lines

_(2) For each pair of chunks (path1 * path2)_

* Intersect chunks to check if there is an intersection

As seen in the algorithm outlined above there is a huge improvement to handle straight lines. Right now, they are converted to bezier curves and cut into chunks. On each of these operations a margin of error may occur during rounding (cf. https://github.com/bpmn-io/path-intersection/issues/7)

__Describe the solution you'd like__

Investigate if we can optimize for line to line intersections.

__Describe alternatives you've considered__

Keep stuff as is :christmas_tree:.

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #9

While working on my slack time topic, I figured this issue is rather easy to fix.

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
We will not be able to merge this with appropriate test coverage (for all scenarios).

**Comment by nikku** [comment]
This may not be testable. In this case, maybe you can elaborate on the optimization, i.e. by adding a comment to the source code.

**Comment by nikku** [comment]
Goal: Make it possible to understand the optimizations when we look into the code a few month from now.

**Comment by oguzeroglu** [comment]
Existing tests having lines without tangents cover this (for instance the first test), as this should not effect the results but only the execution time.

I added comments to the code.

**Comment by nikku** [comment]
Thanks. Great contribution.

**Comment by nikku** [comment]
Note that this only optimizes straight lines in the horizontal / vertical case. It does not optimize these lines if they are diagonal, for instance: 

image

For these diagonal straight lines, we could set the segment count to `1`, too. This could be an additional improvement.

**Comment by oguzeroglu** [comment]
Thanks! I realized I misused the term tangent in the title. It should be "slope" instead :) That's what I basically meant.

**Pull request merged**
